name: 'Build Rust Binary'
description: 'Build a Rust binary for a specific target with cross-compilation support'
inputs:
  target:
    description: 'Rust target triple'
    required: true
  os:
    description: 'GitHub Actions runner OS'
    required: true
  binary_name:
    description: 'Name of the binary to build'
    required: true
  archive_format:
    description: 'Archive format (tar.gz or zip)'
    required: true
  use_cross:
    description: 'Whether to use cross-compilation'
    required: true
  ref:
    description: 'Git reference to checkout'
    required: false
    default: ${{ github.ref }}
  config_file:
    description: 'Path to release config file'
    required: false
    default: '.github/release-config.yml'
outputs:
  has_binary:
    description: 'Whether the binary was successfully built'
    value: ${{ steps.check-binary.outputs.has_binary }}
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy
        target: ${{ inputs.target }}

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache target
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-target-${{ inputs.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-${{ inputs.target }}-
          ${{ runner.os }}-target-

    - name: Clean disk space
      shell: bash
      run: |
        # Remove large cargo registry files that aren't needed
        if [ "${{ runner.os }}" = "Windows" ]; then
          # Windows commands (using bash on Windows)
          rm -rf ~/.cargo/registry/src
          # Show disk usage
          df -h || echo "df not available on Windows"
          du -sh ~/.cargo/* 2>/dev/null | sort -hr | head -5 || true
        else
          # Linux/macOS commands
          rm -rf ~/.cargo/registry/src
          # Clean system package cache
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get clean
          fi
          # Show disk usage
          df -h
          du -sh ~/.cargo/* 2>/dev/null | sort -hr | head -5 || true
        fi

    - name: Install zig and cargo-zigbuild
      if: inputs.use_cross == 'true'
      shell: bash
      run: |
        # Install zig
        wget -q https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
        tar -xf zig-linux-x86_64-0.12.0.tar.xz
        sudo mv zig-linux-x86_64-0.12.0 /opt/zig
        sudo ln -s /opt/zig/zig /usr/local/bin/zig
        zig version
        # Install cargo-zigbuild
        cargo install cargo-zigbuild --locked
        rustup target add ${{ inputs.target }}

    - name: Build release binary (cross)
      if: inputs.use_cross == 'true'
      shell: bash
      run: cargo zigbuild --release --target ${{ inputs.target }} --verbose
      env:
        RUSTFLAGS: ""

    - name: Build release binary (cargo)
      if: inputs.use_cross != 'true'
      shell: bash
      run: cargo build --release --verbose --target ${{ inputs.target }}
      env:
        RUSTFLAGS: ""

    - name: Check built binary
      id: check-binary
      shell: bash
      run: |
        BIN_PATH=target/${{ inputs.target }}/release/${{ inputs.binary_name }}
        if [ -f "$BIN_PATH" ]; then
          echo "has_binary=true" >> $GITHUB_OUTPUT
          echo "✅ Found binary at $BIN_PATH"
        else
          echo "has_binary=false" >> $GITHUB_OUTPUT
          echo "::warning::Binary not found at $BIN_PATH; skipping packaging for ${{ inputs.target }}"
        fi

    - name: Create release directory
      if: steps.check-binary.outputs.has_binary == 'true'
      shell: bash
      run: |
        mkdir -p release
        if [ "${{ runner.os }}" = "Windows" ]; then
          cp target/${{ inputs.target }}/release/${{ inputs.binary_name }} release/
        else
          cp target/${{ inputs.target }}/release/${{ inputs.binary_name }} release/
        fi

    - name: Create README for release
      if: steps.check-binary.outputs.has_binary == 'true'
      shell: bash
      run: |
        # Read config for project info, fallback to defaults
        PROJECT_NAME="${{ inputs.binary_name }}"
        HOMEPAGE="https://github.com/${{ github.repository }}"

        if [ -f "${{ inputs.config_file }}" ]; then
          # Try to parse YAML - fallback to defaults for now
          DESCRIPTION="Binary release for ${{ inputs.binary_name }}"
        else
          DESCRIPTION="Binary release for ${{ inputs.binary_name }}"
        fi

        cat > release/README.md << EOF
        # ${{ inputs.binary_name }}

        ## Installation

        ### Linux

        Two Linux binaries are available:

        | Binary | Best For |
        |--------|----------|
        | \`${{ inputs.binary_name }}-x86_64-unknown-linux-musl.tar.gz\` | Universal - containers, CI/CD, older distributions |
        | \`${{ inputs.binary_name }}-x86_64-unknown-linux-gnu.tar.gz\` | FIPS/compliance environments requiring dynamic linking |

        **Recommended (musl/static - works everywhere):**
        \`\`\`bash
        tar -xzf ${{ inputs.binary_name }}-x86_64-unknown-linux-musl.tar.gz
        sudo mv ${{ inputs.binary_name }} /usr/local/bin/
        ${{ inputs.binary_name }} --version
        \`\`\`

        **For FIPS/compliance (glibc - requires glibc 2.38+):**
        \`\`\`bash
        tar -xzf ${{ inputs.binary_name }}-x86_64-unknown-linux-gnu.tar.gz
        sudo mv ${{ inputs.binary_name }} /usr/local/bin/
        ${{ inputs.binary_name }} --version
        \`\`\`

        ### Windows
        Extract the ZIP file and add to your PATH, or run from the extracted directory:
        \`\`\`powershell
        # Extract ${{ inputs.binary_name }}-x86_64-pc-windows-msvc.zip
        # Add to PATH or run from extracted directory
        ${{ inputs.binary_name }}.exe --version
        \`\`\`

        For more information, visit: $HOMEPAGE
        EOF

    - name: Create archive
      if: steps.check-binary.outputs.has_binary == 'true'
      shell: bash
      run: |
        cd release
        ARCHIVE_NAME="${{ inputs.binary_name }}-${{ inputs.target }}.${{ inputs.archive_format }}"
        if [ "${{ inputs.archive_format }}" = "tar.gz" ]; then
          tar -czf ../$ARCHIVE_NAME *
        else
          # Use PowerShell Compress-Archive on Windows
          if [ "${{ runner.os }}" = "Windows" ]; then
            powershell -Command "Compress-Archive -Path * -DestinationPath ../$ARCHIVE_NAME -Force"
          else
            zip -r ../$ARCHIVE_NAME *
          fi
        fi
        cd ..
        ls -lh $ARCHIVE_NAME

    - name: Upload artifact
      if: steps.check-binary.outputs.has_binary == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.binary_name }}-${{ inputs.target }}.${{ inputs.archive_format }}
        path: ${{ inputs.binary_name }}-${{ inputs.target }}.${{ inputs.archive_format }}
        retention-days: 30
